### ISSUE TITLE
Unclear relation of a `service` property to controller document

### ISSUE THREAD

**Issue by filip26** [w3c/controller-document#110]
Hi,
there is a section defining [Services](https://www.w3.org/TR/controller-document/#services)  but `service` property is not listed as a document [property](https://www.w3.org/TR/controller-document/#controller-documents).  Does that mean that the property definition is not normative? and its definition is missing from context `https://www.w3.org/ns/controller/v1`.

(DID Document defines `service` as `https://www.w3.org/ns/did#service`)

**Comment by msporny** [comment]
PR #112 has been raised to address this issue. This issue will be closed once PR #112 has been merged.

**Comment by msporny** [comment]
PR #112 has been merged, closing.
