### ISSUE TITLE
JSON-LD context defines `alsoKnownAs` in wrong namespace?

### ISSUE THREAD

**Issue by trwnh** [w3c/controller-document#111]
https://www.w3.org/ns/controller/v1 defines `alsoKnownAs` as `https://w3id.org/security#alsoKnownAs` but as far as I can tell the Security Vocabulary doesn't actually define this term anywhere.

The term originates from the ActivityStreams namespace `https://www.w3.org/ns/activitystreams#alsoKnownAs` and has two conflicting sets of semantics. One is defined in DID Core: https://www.w3.org/TR/did-core/#also-known-as to mean a set of URIs or DIDs that refer to the same subject (basically "aliases"). The other is used by Mastodon and the fediverse to mean that two ActivityPub actors have the same controller, similar to the rel=me link relation (and it is used to authorize follower migrations).

I am vaguely assuming that this could be an attempt to subvert the unfortunate semantic conflict from the previous paragraph, but it could also be a simple error. In any case, it's probably something that should be resolved either by changing sec:alsoKnownAs to as:alsoKnownAs (and adopting DID Core semantics), or by actually defining it in the Security Vocabulary, or by defining it in some other vocabulary and changing the namespace to reflect that new definition.

**Comment by dlongley** [comment]
There's just a simple bug in the context. The term should be using the activitystreams vocabulary and it should be using the same definition that is in the DID v1 context (https://www.w3.org/ns/did/v1), which also matches the activitystreams context.

**Comment by msporny** [comment]
Yeah, it's a bug, we'll fix it. Thanks for catching it, @trwnh! :)

**Comment by msporny** [comment]
PR #113 has been raised to address this issue. This issue will be closed once PR #113 has been merged.

**Comment by msporny** [comment]
PR #113 has been merged, closing.
