### ISSUE TITLE
Ambiguous parameter comparison definitions

### ISSUE THREAD

**Issue by himorin** [w3c/controller-document#130]
section 2.2.2 Multikey
https://w3c.github.io/controller-document/#Multikey
and section 2.2.3 JsonWebKey
https://w3c.github.io/controller-document/#JsonWebKey

defined `type` as
> The value of the type property MUST contain the string Multikey. 

This 'MUST contain' is ambiguous on string comparison point of view, and should be replaced with `MUST be identical to` (or something the spec wanted to state) and refer INFRA definition.

**Comment by msporny** [comment]
Fixed in 9b500dfc89efee805879b23846c09456b0af8767. Closing.

**Comment by himorin** [comment]
propose to use [one of defined term in INFRA](https://infra.spec.whatwg.org/#string-is) than just `is set to`
