### ISSUE TITLE
Usage of sha3-512 in the "Contexts and Vocabularies" section

### ISSUE THREAD

**Issue by iherman** [w3c/controller-document#15]
(This issue is relevant in case that section remains in the document, see #10.)

This section seems to be based on an earlier version of the relevant section in the DI spec: it still includes references to sha3-512, which should be removed.

**Comment by selfissued** [comment]
I'm fine removing sha3-512 if that aligns the spec with our other specs.

**Comment by msporny** [comment]
Fixed in 7c8ac930fd1941a4ee0ba156bfd55a26bdeb4312, closing.
