### ISSUE TITLE
Add the SRI datatype?

### ISSUE THREAD

**Issue by iherman** [w3c/controller-document#20]
At the moment, that data type is defined in the VC spec. Strictly speaking, that is fine, because I do not know of any other reference to the datatype than the related resource property (which is defined in the VCDM) but I feel that it is more in the "spirit" of this controller document to list the SRI specification alongside the, say, `multibase` definition.

**Comment by selfissued** [comment]
Are there any other uses of SRI in any of our specifications?

**Comment by iherman** [comment]
> Are there any other uses of SRI in any of our specifications?

Yes. See the table on `relatedResource` in [§5.3 Integrity of Related Resources](https://www.w3.org/TR/vc-data-model-2.0/#integrity-of-related-resources).

If my memory serves me well, there wasn't any consensus on a single representation of the digest of the resource, hence the addtion of SRI.

I do not think the representation issue should be re-opened. No new consideration has come up that'd warrant reopening it.

**Comment by iherman** [comment]
Oops, sorry. I misread your question, somehow did not see the "other".

The correct answer is then, "no".

That being said, I would still prefer to move it to this document. It is the kind of general property/datatypes that may become generally useful for other purposes in the future for the VC ecosystem.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-8) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.8. Add the SRI datatype? (issue controller-document#20)

_See github issue [controller-document#20](https://github.com/w3c/controller-document/issues/20)._




**Brent Zundel:** next, #20, add the SRI datatype?  

**Manu Sporny:** I prefer not to move it since we don't use SRI in Controller Document.  
… the most pure thing to do is put it in Data Integrity spec but there were objections to that before so we decided to move it to where digestSRI and digestMultibase used, that was VCDM.  
… we don't use related resource or digestMultibase in Controller Document specification.  
… Controller Document does define Multibase and Multihash, but does not have relatedResource, which is the only place the SRI datatype is used.  
… I think they're in the right places.  
… If we move the SRI datatype into Controller Document, we don't talk about it anywhere else in that spec.  

**Brent Zundel:** proposal is to close this issue with no action?  

**Manu Sporny:** Correct.  

**Brent Zundel:** Any opposition to marking this issue closed?  
… hearing none, marked pending closed.  
… next up, horizontal review tracking issues.  

</details>

**Comment by iherman** [comment]
Pending close has been set two weeks ago, I do not object; closing.
