### ISSUE TITLE
(Minor) Data model reference?

### ISSUE THREAD

**Issue by iherman** [w3c/controller-document#21]
I was wondering how the VCDM reference landed in the list of formal references (although only as informal). I did not see any trace of it in the text itself...

It would be probably "cleaner" if that reference didn't appear there.

**Comment by selfissued** [comment]
I agree with this.

**Comment by selfissued** [comment]
@iherman can you please create a PR for this?  Thanks.

**Comment by iherman** [comment]
The problem comes from the very last paragraph of [§ Contexts as Vocabularies](https://www.w3.org/TR/controller-document/#contexts-and-vocabularies) that refers to the VCDM spec on processing JSON-LD contexts and vocabularies further. Although informative (is that o.k., b.t.w.?) it refers to major sections in the VCDM, so a dependency is established.

I actually wonder whether the issue is much more complex than I realized at first. Looking at the section as a whole, it describes references to vocabularies, content digests, etc, that are all VCDM specific. I am not sure that is appropriate for this document, which should probably stay more generic. At the minimum, the corresponding DID information should also be added to the document.

This must be extensively discussed before raising a PR.

cc @msporny

**Comment by msporny** [comment]
> This must be extensively discussed before raising a PR.

We [discussed this during the call this week](https://www.w3.org/2024/07/31-vcwg-minutes.html#t13). The conclusion was that we could remove most, but not all of the VCDM references. If we wanted to remove all of the VCDM references, we'd end up having to remove sections that specifically talk about specifications that build on top of the Controller Document specification.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-7) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.7. (Minor) Data model reference? (issue controller-document#21)

_See github issue [controller-document#21](https://github.com/w3c/controller-document/issues/21)._




**Brent Zundel:** next up #21 raised by Ivan.  
… we have an informative reference to VCDM, copy-paste artifact, proposal is to remove that.  
… hopefully Ivan will act on that and move forward.  

**Manu Sporny:** I was going through the spec, we can remove most of the references, but we have a section on binding to a physical identity that references VCDM, in content integrity we say that if you want to do content integrity read about it in VCDM, we could point to data integrity, this feels like if someone blanket removes these statements it's an issue, probably can remove most of them.  

**Brent Zundel:** that comment will get into the issue and hopefully be reflected in Ivan's PR.  

</details>

**Comment by iherman** [comment]
@msporny indeed, this is more complex than it seemed. I may be fine keeping some VC references but, then, we should have references to the DID spec as well (when applicable). I know this document is aimed at a larger audience but, at least for now, one of its primary purposes is to make a bridge between those two...

I am looking forward to the PR.

**Comment by msporny** [comment]
PR #82 has been raised to address this issue. This issue will be closed once PR #82 has been merged.

**Comment by msporny** [comment]
PR #82 has been merged, closing.
