### ISSUE TITLE
Proper location for Multikey definition(s)

### ISSUE THREAD

**Issue by iherman** [w3c/controller-document#27]
At the moment, the formal specification of the Multikey format is in the [DI spec](https://www.w3.org/TR/vc-data-integrity/#multikey). However, this definition is only a high level definition: 

> The Multikey data model is a specific type of [verification method](https://www.w3.org/TR/vc-data-integrity/#dfn-verification-method) that encodes key types into a single binary stream that is then encoded as a Multibase value as described in Section [2.4 Multibase](https://www.w3.org/TR/vc-data-integrity/#multibase-0).

It does not say _how_ a key is encoded. There is an example in the section for Ed25519 key, but it is unclear where that definition comes from.

In fact, those details are defined in the respective cryptosuite specifications, see [ECDSA](https://www.w3.org/TR/vc-di-ecdsa/#multikey), [EdDSA, a.k.a. Ed25519 key](https://www.w3.org/TR/vc-di-eddsa/#multikey), and [BBS](https://www.w3.org/TR/vc-di-bbs/#multikey). And this is fine, but it very much sounds like tribal knowledge; reading the DI spec does not clarify that. So, in my view, there should be an information in the [Multikey section of the DI spec](https://www.w3.org/TR/vc-data-integrity/#multikey) making it clear that for specific keys, the reader should see the respective cryptosuite specification.

---

That being said... it may be possible to make a slightly more elaborated (but still editorial) change. To take the aforementioned Ed25519 key, the Multikey encoding of that key should not be dependent on the EdDSA cryptosuite. What if someone wants to define a different cryptosuite but using the same elliptical curve, i.e., the same Ed25519 key? Should that someone refer to the EdDSA cryptosuite spec for the encoding? Should that someone define his/her own multikey definition? What if someone wants to use a multikey representation of the Ed25519 key for a very different purpose?

It may be a better choice to extract the multikey definitions from the cryptosuite specifications, and move them to the DI spec, as subsections of the [Multikey section of the DI spec](https://www.w3.org/TR/vc-data-integrity/#multikey). It would make this definition independent of the key usage, giving a more general purpose for the specification of multikeys.

**Comment by msporny** [comment]
PR #28 has been raised to address this issue. This issue will be closed once PR #28 has been merged.

**Comment by msporny** [comment]
PR #28 has been merged, closing.
