### ISSUE TITLE
Note that controllers can control multiple keys

### ISSUE THREAD

**Issue by msporny** [w3c/controller-document#45]
Moving this old issue marker over from the Data Integrity specification to this specification:

Add a note indicating that this specification should not be construed to indicate that public key controllers should be restricted to a single public key or that systems that use this spec and involve real people should identify each person as only ever being a single entity rather than perhaps N entities with M keys. There are no such restrictions and in many cases those kinds of restrictions are ill-advised due to privacy considerations.

**Comment by selfissued** [comment]
This certainly seems true on the face of it.  I'm curious what a PR effecting this note will do.

**Comment by msporny** [comment]
PR #83 has been raised to address this issue. This issue will be closed once PR #83 has been merged.

**Comment by msporny** [comment]
PR #83 has been merged, closing.
