### ISSUE TITLE
Authentication definition overly specific

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#48]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#terminology
In the "authentication" definition, I believe that "to a verifier" should be deleted.  An entity can authenticate to parties other than a verifier.

**Comment by msporny** [comment]
The "verifier" is the role that does the checking on whether the authentication is valid.

**Comment by selfissued** [comment]
The verifier is one of the parties to which authentication can occur.  Your response doesn't address the point that other parties could be authenticated to as well.

**Comment by msporny** [comment]
It does address the point. The "verifier" is a role that an entity plays when they are performing a verification. When they are verifying, they're the "verifier"... they can't be anything else.

We could add a definition similar to https://w3c.github.io/vc-data-model/#dfn-verifier and link to it -- would that address your concern?

**Comment by selfissued** [comment]
Yes, adding such a definition is a good suggestion.

**Comment by selfissued** [comment]
I believe this is ready for a PR to add the proposed definition (and to use it).

**Comment by selfissued** [comment]
OK, I've thought about this some more.  I no longer want to add a definition for "verifier" because the definition we'd add would be different than the "verifier" definition in VCDM.  Having two different definitions for the same word would unnecessarily confuse people.

In fact, I believe part of why the sentence stuck me as being in need of repair is that its use of the term "verifier" had a different meaning than the meaning in VCDM.

I now propose that we change "A process by which an entity can prove to a verifier" to "A process by which an entity can prove to a verifying party".  Would that work for people?

**Comment by msporny** [comment]
PR #81 has been raised to address this issue. This issue will be closed once PR #81 has been merged.

**Comment by msporny** [comment]
PR #81 has been merged, closing.
