### ISSUE TITLE
Replace inline issues with GitHub issues

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#52]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#data-model
Also, let's please replace all inline issues with actual GitHub issues so we can more easily track progress on them.

There are currently two of them.

**Comment by msporny** [comment]
Please raise the two as issues and close this issue.

**Comment by msporny** [comment]
Replacement issues have been raised in #72 and #73, closing.
