### ISSUE TITLE
Missing link to verification method type definition

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#58]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#verification-material
The use of "type" here is also not an actionable hyperlink.

**Comment by msporny** [comment]
It's not meant to be a hyperlink, it's meant to be code mark up.

**Comment by selfissued** [comment]
You're missing the point of the issue.  There needs to be an actionable way to find the verification method type definition.  I'll change the title to a more descriptive one, if you'd like to suggest one.

**Comment by msporny** [comment]
> You're missing the point of the issue.

I'm not, I understand what you're requesting, I just disagree with it.

> There needs to be an actionable way to find the verification method type definition. I'll change the title to a more descriptive one, if you'd like to suggest one.

The `type` is explained in the section immediately preceding the one you are commenting on: 

https://w3c.github.io/controller-document/#verification-methods

If folks want to know what the "type" field means in a "Verification Method", they can go to the section titled "Verification Method" and then look at what the definition of "type" is, which is here:

https://w3c.github.io/controller-document/#verification-methods

The specification uses CODE markup when speaking about literal values in a controller document. The use of the CODE block around the `type` property you mentioned is consistent with how it is used elsewhere in the specification. Changing it there would make that text inconsistent with all the other parts in the specification that use the CODE markup.

**Comment by selfissued** [comment]
The previous section that you reference has this definition for type:
> The value of the type property MUST be a [string](https://infra.spec.whatwg.org/#string) that references exactly one [verification method](https://w3c.github.io/controller-document/#dfn-verification-method) type.

Following the link there to [verification method](https://w3c.github.io/controller-document/#dfn-verification-method), that definition doesn't even mention the type.  It's a dead-end for readers looking for what verification method types are.

The point of this issue isn't about hyperlinking.  It's about whether readers can easily find a list of verification method types that are expected to be used.  It turns out that the specification defines `publicKeyMultibase`, `secretKeyMultibase`, `publicKeyJwk`, and `secretKeyJwk` as possible `type` values.  But nowhere is there a section or definition called "Verification Method Types".

I propose that we write a short such section, whose content is something like:
> This specification defines the verification method types `publicKeyMultibase`, `secretKeyMultibase`, `publicKeyJwk`, and `secretKeyJwk` in Sections 2.2.2 and Sections 2.2.3.  Other verification method types MAY be defined and used.

I'm willing to write the PR.

**Comment by dlongley** [comment]
@selfissued,

The verification method types are in the verification method section, following the "Verification Material" section:

https://w3c.github.io/controller-document/#multikey
https://w3c.github.io/controller-document/#jsonwebkey

Note that the above things you listed as types are not verification method types, but sub-properties of the above types.

The sections above say this as their first sentence each:

"The Multikey data model is a specific type of verification method..."

and

"The JSON Web Key (JWK) data model is a specific type of verification method..."

Is more than this needed? Perhaps a sentence in the "type" definition of verification method that says "This specification defines the following types: <link to Multikey>, <link to JsonWebKey>"? I don't know that I feel it's personally needed, but perhaps that's one option to help others who do feel it's needed.

**Comment by selfissued** [comment]
I suggest we incorporate @dlongley's suggestion.
