### ISSUE TITLE
Make Multibase and Multihash sections subsections

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#6]
There are currently top-level Multibase and Multihash sections, which seems out of place.  (They aren't that way in the Data Integrity spec, for instance.)  One idea is to move them to be subsections of the existing Algorithms section.

**Comment by msporny** [comment]
Let's move the sections into the Data Model section, and leave the base encoding algorithms in the algorithms section.

**Comment by msporny** [comment]
Fixed in 2d145196b5bbeac7e5640a6f14dd7e9babd2ed0b.
