### ISSUE TITLE
Delete non-actionable statement about authentication

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#61]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#authentication
This sentence doesn't provide actionable information: "If authentication is established, it is up to the application to decide what to do with that information."  It should either be deleted or updated to do so.

**Comment by msporny** [comment]
That sentence was added because a previous reviewer wanted to know what happens when authentication is established.

**Comment by selfissued** [comment]
And this sentence doesn't answer the question of what happens when authentication is established, nor should it.  The spec will be better off without this.

**Comment by selfissued** [comment]
How about replacing the whole sentence with "The processing performed following authentication is application-specific."?

**Comment by msporny** [comment]
In order to make progress at W3C TPAC, I am suggesting that this issue is "editorial" and can be resolved during the Candidate Recommendation phase. The VCWG will discuss this issue at W3C TPAC to see if the "during CR" determination is correct.

**Comment by msporny** [comment]
PR #122 has been raised to address this issue. This issue will be closed once PR #122 has been merged.

**Comment by msporny** [comment]
PR #122 has been merged, closing.
