### ISSUE TITLE
Representation of length of cryptographic hash unspecified

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#65]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#multihash
This section says that "2) the length of the cryptographic hash" is included but it doesn't define the representation of the length used.  For instance, is a single-byte binary value representing the number of bytes used?  A two-byte value representing the number of bits?  Please specify.

**Comment by selfissued** [comment]
I agree that this is ready for a PR.  @msporny, can you take this one since you likely know the answer off the top of your head?

**Comment by msporny** [comment]
PR #88 has been raised to address this issue. This issue will be closed once PR #88 has been merged.

**Comment by msporny** [comment]
PR #88 has been merged, closing.
