### ISSUE TITLE
Multibase character definition missing

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#69]
https://www.w3.org/TR/2024/WD-controller-document-20240817/#multibase
The term "multibase character" is used without being defined and without the term being a hyperlink to a definition.

**Comment by selfissued** [comment]
I agree that this is ready for a PR.  @msporny, can you take this since its probably easier for you to define this than me.

**Comment by msporny** [comment]
PR #89 has been raised to address this issue. This issue will be closed once PR #89 has been merged.

**Comment by msporny** [comment]
PR #89 has been merged, closing.
