### ISSUE TITLE
Note that hash values might change during Candidate Recommendation

### ISSUE THREAD

**Issue by selfissued** [w3c/controller-document#73]
This issue replaces an issue described within the specification itself at https://www.w3.org/TR/2024/WD-controller-document-20240817/#contexts-and-vocabularies.

This is part of addressing #52.

The section lists cryptographic hash values that might change during the Candidate Recommendation phase based on implementer feedback that requires the referenced files to be modified.

**Comment by msporny** [comment]
PR #74 has been raised to address this issue. This issue will be closed once that PR is merged.

**Comment by msporny** [comment]
PR #74 has been merged, closing.
